### ISSUE TITLE
Dropdown buttons do not render properly

### ISSUE THREAD

**Issue by StormPooper** [davewarfel/Bootstrap-MCE-CSS#2]
Great plugin, but I've noticed a problem. I have the following code in my page:

```
<div class="btn-group">
<button class="btn btn-success dropdown-toggle" type="button" data-toggle="dropdown"><i class="fa fa-download fa-lg"></i> Download <i class="fa fa-caret-down"></i></button>
<ul class="dropdown-menu" role="menu">
    <li><a title="Download from Dropbox" href="http://dl.dropbox.com/u/55442605/OEM_Brander.exe" data-toggle="collapse" data-target="#"><i class="fa fa-dropbox fa-fw"></i> Dropbox</a></li>
    <li><a title="Download from Box" href="http://www.box.com/s/lzk8tjskzbz18sjc89xj" target="_blank" data-toggle="collapse" data-target="#"><i class="fa fa-cloud-download fa-fw"></i> Box</a></li>
    <li><a title="Download from FileForum" href="http://fileforum.betanews.com/detail/OEM-Brander/1323565585/1" data-toggle="collapse" data-target="#"> <i class="fa fa-cloud-download fa-fw"></i> FileForum</a></li>
    <li><a title="Download directly" href="http://www.stormpoopersmith.com/files/OEM_Brander.exe" data-toggle="collapse" data-target="#"><i class="fa fa-download fa-fw"></i> Direct</a></li>
</ul>
</div>
```

It renders fine on the page, but in the editor using your plugin it just shows a basic button and a separate list below (note I have another plugin for the FontAwesome icons in the editor):
![image](https://f.cloud.github.com/assets/1657182/1897001/898ad2ba-7bc6-11e3-83f4-6284a11cf3f2.png)

The same thing happens if you copy the example from the Bootstrap components page.

**Comment by davewarfel** [comment]
Thanks for pointing that out, Daniel. What do you think would make the most sense to happen in this case?

I would think you'd want to just completely hide all the dropdown items, right? I can add a `display:none;` to all elements with a class of `dropdown-menu`. I think that would be the best solution. Your thoughts?

What plugin are you using to display FontAwesome icons?

**Comment by StormPooper** [comment]
Yeah, I think so, I don't think there's a neat way of showing the items while making it clear without implementing the full button functionality, which wouldn't really work in something like TinyMCE anyway. It might be worth limiting hiding the class to only when it's within a div with the 'btn-group' class though, so it's not going to clash with custom classes people may be using..

I'm using [WP Visual Icon Fonts](http://wordpress.org/plugins/wp-visual-icon-fonts/) for the Font Awesome icons.

**Comment by StormPooper** [comment]
No longer actively developed.

**Comment by StormPooper** [comment]
No longer actively developed.
